window.HermeneiaAmbiguo = (() => {
  'use strict';
  const Core=window.HermeneiaCore;
  const normalize=w=>String(w||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const CLOSED=new Set(('a o os as um uma uns umas de do da dos das em no na nos nas por para com sem sobre sob entre até desde e ou mas porem porém contudo que se como quando onde quem qual quais ao aos já ja não nao sim também tambem então entao pois porque porquanto mais menos muito pouco todo toda todos todas este esta estes estas esse essa esses essas aquele aquela aqueles aquelas isso isto aquilo eu tu ele ela nós nos vós vos eles elas me te lhe lhes meu minha meus minhas teu tua teus tuas seu sua seus suas nosso nossa nossos nossas dele dela deles delas próprio propria próprio').split(/\s+/).map(normalize));
  const hashInt=s=>{let h=2166136261>>>0;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return h>>>0};
  const splitSentences=text=>String(text||'').replace(/\r/g,'').replace(/\n+/g,' ').split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);
  const WORD_RE=/[A-Za-zÀ-ÖØ-öø-ÿ]+(?:-[A-Za-zÀ-ÖØ-öø-ÿ]+)*/g;
  function tokenize(sentence){const out=[];let m;WORD_RE.lastIndex=0;while((m=WORD_RE.exec(sentence)))out.push({raw:m[0],norm:normalize(m[0]),cap:/^[A-ZÀ-Ö]/.test(m[0])});return out}
  function buildCorpus(text,opts={}){const windowN=opts.window||4,sentences=splitSentences(text),bySentence=sentences.map(tokenize),freq={},cooc={},occurrences={};let total=0;bySentence.forEach((toks,si)=>toks.forEach((t,ti)=>{freq[t.norm]=(freq[t.norm]||0)+1;total++;(occurrences[t.norm]=occurrences[t.norm]||[]).push({sent:si,pos:ti,raw:t.raw})}));bySentence.forEach(toks=>{for(let i=0;i<toks.length;i++)for(let j=Math.max(0,i-windowN);j<=Math.min(toks.length-1,i+windowN);j++){if(i===j)continue;const key=toks[i].norm+'\u0001'+toks[j].norm;cooc[key]=(cooc[key]||0)+1}});return{text,sentences,bySentence,freq,cooc,total,occurrences,window:windowN}}
  function ppmi(stats,a,b){const cab=stats.cooc[a+'\u0001'+b]||0;if(!cab)return 0;const N=stats.total||1,pa=(stats.freq[a]||0)/N,pb=(stats.freq[b]||0)/N,pab=cab/N;if(!pa||!pb)return 0;const v=Math.log(pab/(pa*pb));return v>0?v:0}
  function vectorOf(stats,word,opts={}){const v={},seen={},minFreq=opts.minFreq||1;Object.keys(stats.cooc).forEach(key=>{const [a,b]=key.split('\u0001');if(a!==word||seen[b]||(stats.freq[b]||0)<minFreq)return;seen[b]=1;const w=ppmi(stats,word,b);if(w>0)v[b]=w});return v}
  function cosine(v1,v2){let dot=0,n1=0,n2=0;Object.keys(v1).forEach(k=>{n1+=v1[k]*v1[k];if(v2[k])dot+=v1[k]*v2[k]});Object.keys(v2).forEach(k=>n2+=v2[k]*v2[k]);return n1&&n2?dot/Math.sqrt(n1*n2):0}
  function collocatesOf(stats,word,opts={}){const topK=opts.topK||30,wv=vectorOf(stats,word,opts);return Object.keys(wv).filter(w=>!CLOSED.has(w)&&w.length>2&&w!==word).sort((a,b)=>wv[b]-wv[a]||a.localeCompare(b)).slice(0,topK).map(w=>({word:w,assoc:wv[w]}))}
  function stableOrder(nodes,it){return nodes.slice().sort((a,b)=>(hashInt(a+'|'+it)-hashInt(b+'|'+it))||a.localeCompare(b))}
  function labelPropagation(nodes,weight,iters=15){const label={};nodes.forEach((n,i)=>label[n]='c'+i);for(let it=0;it<iters;it++){let changed=false;for(const n of stableOrder(nodes,it)){const tally={};nodes.forEach(m=>{if(m===n)return;const w=weight(n,m);if(w<=0)return;const l=label[m];tally[l]=(tally[l]||0)+w});let best=null,bestW=-1;Object.keys(tally).sort().forEach(l=>{if(tally[l]>bestW){bestW=tally[l];best=l}});if(best&&best!==label[n]){label[n]=best;changed=true}}if(!changed)break}const groups={};nodes.forEach(n=>(groups[label[n]]=groups[label[n]]||[]).push(n));return Object.keys(groups).sort().map(k=>groups[k])}
  function avg(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
  function separationScore(groups,weight){const within=[],between=[];for(let gi=0;gi<groups.length;gi++){for(let i=0;i<groups[gi].length;i++)for(let j=i+1;j<groups[gi].length;j++)within.push(weight(groups[gi][i],groups[gi][j]));for(let gj=gi+1;gj<groups.length;gj++)groups[gi].forEach(a=>groups[gj].forEach(b=>between.push(weight(a,b))))}return avg(within)-avg(between)}
  function bestClustering(words,denseWeight){const n=words.length;if(n<4)return null;const ks=[2,3,4,5,6,8,10,Math.round(n/3),Math.round(n/2)].filter((k,i,a)=>k>=2&&k<n&&a.indexOf(k)===i);let best=null;ks.forEach(k=>{const neigh={};words.forEach(a=>{neigh[a]={};words.filter(b=>b!==a).map(b=>({b,w:denseWeight(a,b)})).sort((x,y)=>y.w-x.w||x.b.localeCompare(y.b)).slice(0,k).forEach(r=>neigh[a][r.b]=r.w)});const sparse=(a,b)=>Math.max(neigh[a]?.[b]||0,neigh[b]?.[a]||0),groups=labelPropagation(words,sparse).filter(g=>g.length>=2);if(groups.length<2)return;const sep=separationScore(groups,denseWeight);if(!best||sep>best.sep)best={k,groups,sep}});return best}
  function groupsToSenses(groups,stats,word,collocates){const assoc={};collocates.forEach(c=>assoc[c.word]=c.assoc);return groups.map((members,i)=>{const centroid={};members.forEach(m=>{const v=vectorOf(stats,m);Object.keys(v).forEach(k=>centroid[k]=(centroid[k]||0)+v[k]/members.length)});const label=members.slice().sort((a,b)=>(assoc[b]||0)-(assoc[a]||0)||a.localeCompare(b)).slice(0,5);return{id:'s'+i,members,centroid,label}})}
  function induceSenses(stats,word,opts={}){const coll=collocatesOf(stats,word,opts),min=opts.minCollocates||4;if(coll.length<min)return{ambiguous:false,reason:`poucos colocados (${coll.length})`,senses:[],separation:0};const words=coll.map(c=>c.word),vectors={};words.forEach(w=>vectors[w]=vectorOf(stats,w,opts));const weight=(a,b)=>cosine(vectors[a],vectors[b]),best=bestClustering(words,weight);if(!best)return{ambiguous:false,reason:'não houve separação distribucional estável',senses:[],separation:0};const senses=groupsToSenses(best.groups,stats,word,coll),sep=best.sep;return{ambiguous:senses.length>=2&&sep>(opts.minSeparation??0.02),separation:Math.round(sep*1000)/1000,k:best.k,senses}}
  function localContext(stats,sentIdx,pos,windowN){const toks=stats.bySentence[sentIdx]||[],out=[];for(let k=Math.max(0,pos-windowN);k<=Math.min(toks.length-1,pos+windowN);k++)if(k!==pos)out.push(toks[k].norm);return out}
  function softmax(xs,temp=1){const max=Math.max(...xs,0),exps=xs.map(x=>Math.exp((x-max)/temp)),sum=exps.reduce((a,b)=>a+b,0)||1;return exps.map(e=>e/sum)}
  function classifyOccurrence(stats,word,occurrence,senses,opts={}){if(!senses.length)return[];const ctx=localContext(stats,occurrence.sent,occurrence.pos,opts.window||stats.window),scores=senses.map(s=>{let score=0;ctx.forEach(w=>{if(CLOSED.has(w))return;score+=cosine(vectorOf(stats,w),s.centroid);if(s.members.includes(w))score+=.5});return score});return softmax(scores,opts.temp||.75).map((p,i)=>({sense:senses[i],prob:p})).sort((a,b)=>b.prob-a.prob)}
  function unitForOccurrence(analysis,sentence){const n=Core.norm(sentence);let best=null,bestScore=0;(analysis.units||[]).forEach(u=>{const a=new Set(Core.words(Core.norm(u.analysisText||u.text))),b=new Set(Core.words(n));let common=0;a.forEach(x=>{if(b.has(x))common++});const score=common/Math.max(1,Math.min(a.size,b.size));if(score>bestScore){bestScore=score;best=u.id}});return best}
  function analyzeAnalysis(analysis,opts={}){const stats=buildCorpus(analysis.sourceText,{window:opts.window||4});const candidates=Object.keys(stats.freq).filter(w=>!CLOSED.has(w)&&w.length>3&&(stats.freq[w]||0)>=(opts.minTargetFreq||2)).sort((a,b)=>(stats.freq[b]-stats.freq[a])||a.localeCompare(b)).slice(0,opts.maxTargets||14);const targets=[],byUnit={};candidates.forEach(word=>{const info=induceSenses(stats,word,{topK:opts.topK||24,minCollocates:opts.minCollocates||4,minSeparation:opts.minSeparation??0.025});if(!info.ambiguous)return;const occs=(stats.occurrences[word]||[]).map(o=>{const dist=classifyOccurrence(stats,word,o,info.senses,{window:stats.window}),unitId=unitForOccurrence(analysis,stats.sentences[o.sent]||'');const rec={word,unitId,raw:o.raw,sentence:stats.sentences[o.sent],distribution:dist,separation:info.separation};if(unitId)(byUnit[unitId]=byUnit[unitId]||[]).push(rec);return rec});targets.push({word,frequency:stats.freq[word],separation:info.separation,senses:info.senses.map(s=>({id:s.id,label:s.label,members:s.members})),occurrences:occs})});return{method:'PPMI + grafo de colocados + classificação contextual determinística',stats:{tokens:stats.total,sentences:stats.sentences.length,targetsExamined:candidates.length,ambiguousTargets:targets.length},targets,byUnit}}
  function resolvePossessor(analysis,unitId,opts={}){if(opts.explicitPossessor)return[{who:opts.explicitPossessor,prob:1,reason:'marca possessiva explícita'}];const units=analysis.units||[],idx=units.findIndex(u=>u.id===unitId),scores=new Map();const add=(who,score,reason)=>{if(!who)return;const x=scores.get(who)||{who,score:0,reasons:[]};x.score+=score;x.reasons.push(reason);scores.set(who,x)};if(opts.subjectName)add(opts.subjectName,1,'sujeito da própria oração');for(let i=Math.max(0,idx-3);i<=idx;i++){const u=units[i];(analysis.entities||[]).filter(e=>(e.units||[]).includes(u.id)).forEach(e=>add(e.label||e.name,.55/(1+idx-i),'referente recente'))}(analysis.coreference||[]).filter(c=>c.unit===unitId).forEach(c=>add(c.entity,.9,'correferência estabilizada'));const list=[...scores.values()];const probs=softmax(list.map(x=>x.score),.6);return list.map((x,i)=>({who:x.who,prob:probs[i],reason:[...new Set(x.reasons)].join('; ')})).sort((a,b)=>b.prob-a.prob)}
  return{buildCorpus,ppmi,vectorOf,cosine,collocatesOf,induceSenses,classifyOccurrence,analyzeAnalysis,resolvePossessor};
})();

/* ================================================================
 * REDATOR 2 — Realizador determinístico
 * Só verbaliza conteúdo já estabilizado. Não infere relações novas.
 * ================================================================ */
