function HermeneiaAppBootstrap(){
'use strict';
const Core=window.HermeneiaCore, Realizer=window.HermeneiaRealizer, Hyp=window.HermeneiaHypothesis, LX=window.HermeneiaLexicon, Ambiguo=window.HermeneiaAmbiguo, Redator=window.HermeneiaRedator, Deep=window.HermeneiaDeepParser, Cache=window.HermeneiaCache, HAI=window.HermeneiaAI;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>`${Math.round(Math.max(0,Math.min(1,Number(n)||0))*100)}%`;
const app={analysis:null,apotic:null,comments:[],selection:null,pinned:{},selectedFinals:new Set(),affirmed:null,projectId:null,resourceBundle:null,resourceStatus:null,bibleIndex:null,researchQueries:[],researchResults:[],externalEvidence:[],researchStatus:null,aiHypothesisExplanations:{},aiFinalExplanations:{},aiResearchSynthesis:{},aiStatus:null};

const SAMPLE=`¹⁰ Rogo-vos, irmãos, pelo nome de nosso Senhor Jesus Cristo, que faleis todos a mesma coisa e que não haja entre vós divisões; antes, sejais inteiramente unidos, na mesma disposição mental e no mesmo parecer.\n¹¹ Pois a vosso respeito, meus irmãos, fui informado, pelos da casa de Cloe, de que há contendas entre vós.\n¹² Refiro-me ao fato de cada um de vós dizer: Eu sou de Paulo, e eu, de Apolo, e eu, de Cefas, e eu, de Cristo.\n¹³ Acaso, Cristo está dividido? Foi Paulo crucificado em favor de vós ou fostes, porventura, batizados em nome de Paulo?\n¹⁴ Dou graças a Deus porque a nenhum de vós batizei, exceto Crispo e Gaio;\n¹⁵ para que ninguém diga que fostes batizados em meu nome.\n¹⁶ Batizei também a casa de Estéfanas; além destes, não me lembro se batizei algum outro.\n¹⁷ Porque não me enviou Cristo para batizar, mas para pregar o evangelho; não com sabedoria de palavra, para que se não anule a cruz de Cristo.`;
window.__HERMENEIA_SAMPLE__={title:'1Coríntios 1.10–17',text:SAMPLE};

function setStatus(text,kind=''){$('#statusText').textContent=text;$('#statusDot').className=`status-dot ${kind}`}
function aiProviderLabel(p){return ({native:'Prompt API nativa',webgpu:'WebGPU / Transformers.js',deterministic:'Redator determinístico'}[p]||p||'não detectado')}
async function renderAIStatus(doDetect=false){const box=$('#aiStatus');if(!box)return;let det=null;try{if(doDetect)det=await HAI.detect()}catch(_e){}const st=HAI.status();const xs=[];xs.push(`<span class="ai-pill ${st.status==='ready'?'good':st.lastError?'warn':''}">Ativo: ${esc(aiProviderLabel(st.provider))}</span>`);if(det){xs.push(`<span class="ai-pill ${det.native?'good':'warn'}">Nativo: ${det.native?esc(det.nativeAvailability||'detectado'):'não'}</span>`);xs.push(`<span class="ai-pill ${det.webgpu?'good':'warn'}">WebGPU: ${det.webgpu?'sim':'não'}</span>`)}if(st.model)xs.push(`<span class="ai-pill">${esc(st.model)}</span>`);if(st.lastError)xs.push(`<span class="ai-pill warn">${esc(st.lastError.message||st.lastError)}</span>`);box.innerHTML=xs.join('')}
async function detectAI(){await renderAIStatus(true);setStatus('Capacidades locais detectadas','good')}
async function activateAI(){const btn=$('#activateAIBtn');if(btn)btn.disabled=true;setStatus('Inicializando IA local…','working');try{await HAI.activate($('#aiProviderPref').value,x=>{const p=x?.progress!=null?Math.round(x.progress):null;setStatus(p!=null?`Baixando modelo local · ${p}%`:'Carregando modelo local…','working')});await renderAIStatus(true);setStatus(`IA local ativa · ${aiProviderLabel(HAI.status().provider)}`,'good')}catch(e){window.HermeneiaUI?.showError(e,'IA local');setStatus('IA local indisponível; Redator determinístico permanece ativo','bad')}finally{if(btn)btn.disabled=false}}
function researchContext(limit=8){return (app.externalEvidence.length?app.externalEvidence:app.researchResults).slice(0,limit).map(r=>({origin:'E',title:r.title,url:r.url,domain:r.domain,authority:r.authority,description:r.description,extracted:(r.extracted||[]).slice(0,2)}))}
async function explainHypothesisById(unitId,hypId){if(!app.apotic)return;const h=(app.apotic.local?.[unitId]||[]).find(x=>x.id===hypId),u=app.analysis?.units?.find(x=>x.id===unitId);if(!h||!u)return;const key=unitId+'|'+hypId,box=document.querySelector(`[data-ai-box="${CSS.escape(key)}"]`);if(box)box.innerHTML='<b>Explicando…</b>';const fallback=`Esta hipótese afirma que ${h.statement.replace(/^./,c=>c.toLowerCase())} O suporte de ${pct(h.support)} mede sua compatibilidade com os critérios do motor e não a transforma em verdade final.`;const data={origin:'L/H',unit:{id:u.id,text:u.text},hypothesis:{statement:h.statement,family:h.family,support:h.support,evidence:h.evidence,assumptions:h.assumptions,source:h.source},external:$('#aiResearchEnrich')?.checked?researchContext(4):[]};const out=await HAI.run('explain',data,{fallback});app.aiHypothesisExplanations[key]=out.text;if(box)box.innerHTML=`<b>${esc(aiProviderLabel(out.provider))}</b><div>${esc(out.text)}</div>`}
async function enrichFinalsWithAI(){if(!app.apotic?.finals?.length)return;const useE=$('#aiResearchEnrich')?.checked,ext=useE?researchContext(8):[];setStatus('Explicando construções com IA local…','working');for(const f of app.apotic.finals){const fallback=`Esta construção privilegia ${f.description||f.title}. Ela reúne hipóteses locais com coerência ${pct(f.score)} e deve ser lida como possibilidade global, não como decisão do motor.`;const data={origin:'L/H',construction:{id:f.id,title:f.title,description:f.description,summary:f.summary,score:f.score,anchors:f.anchors,supporting:(f.supporting||[]).slice(0,8).map(x=>({unitId:x.unitId,statement:x.statement,support:x.support,evidence:x.evidence}))},external:ext};const out=await HAI.run(useE&&ext.length?'research':'explain',data,{fallback,maxNewTokens:440});app.aiFinalExplanations[f.id]={text:out.text,provider:out.provider,usesExternal:!!(useE&&ext.length)};await new Promise(r=>setTimeout(r,0))}renderHypothetical();setStatus('Construções explicadas em linguagem humana','good')}
async function enrichTopHypothesesWithAI(){
  if(!app.apotic||!app.analysis)return alert('Execute a análise primeiro.');
  const candidates=[];
  for(const u of app.analysis.units){
    const hs=(app.apotic.local?.[u.id]||[]).slice().sort((a,b)=>b.support-a.support);
    if(hs[0])candidates.push({u,h:hs[0]});
  }
  // Limite deliberado para não disparar dezenas de inferências locais de uma só vez.
  candidates.sort((a,b)=>b.h.support-a.h.support);
  const chosen=candidates.slice(0,Math.min(10,candidates.length));
  if(!chosen.length)return;
  setStatus(`Explicando ${chosen.length} hipóteses principais…`,'working');
  for(let i=0;i<chosen.length;i++){
    const {u,h}=chosen[i], key=u.id+'|'+h.id;
    const fallback=`Nesta unidade, a hipótese mais bem sustentada afirma que ${h.statement.replace(/^./,c=>c.toLowerCase())} O suporte de ${pct(h.support)} expressa compatibilidade com os critérios internos e não uma probabilidade de verdade.`;
    const ext=$('#aiResearchEnrich')?.checked?researchContext(5):[];
    const out=await HAI.run(ext.length?'research':'explain',{origin:'L/H',unit:{id:u.id,text:u.text},hypothesis:{statement:h.statement,family:h.family,support:h.support,evidence:h.evidence,assumptions:h.assumptions,source:h.source},external:ext},{fallback,maxNewTokens:360});
    app.aiHypothesisExplanations[key]=out.text;
    setStatus(`Explicando hipóteses · ${i+1}/${chosen.length}`,'working');
    await new Promise(r=>setTimeout(r,0));
  }
  renderApotic();
  setStatus('Hipóteses principais explicadas em linguagem didática','good');
}
function switchView(name){
  $$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
  const titles={editor:'Mesa de análise',exegesis:'Exegese analítica',apotic:'Apótica',hypothetical:'Relatório hipotético',affirmed:'Derivação afirmada',research:'Aprofundamento externo',audit:'Auditoria',library:'Projetos e recursos'};
  $('#viewTitle').textContent=titles[name]||'Hermeneia';
}
function options(){return {title:$('#title').value.trim()||'Sem título',genre:$('#genre').value,register:$('#register').value,depth:$('#depth').value}}
function hasServer(){return Boolean(window.google&&google.script&&google.script.run)}
function gsCall(name,...args){return new Promise((resolve,reject)=>{if(!hasServer())return reject(new Error('Apps Script indisponível.'));google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(new Error(e?.message||String(e))))[name](...args)})}
function resourceKeys(text){const seen=new Set(),out=[];Core.words(text).forEach(w=>{[Core.resourceKey(w),Core.resourceKey(Core.lemma(w)),Core.resourceKey(Core.nominalLemmaCandidate?Core.nominalLemmaCandidate(w):w)].forEach(k=>{if(k&&k.length>1&&!seen.has(k)){seen.add(k);out.push(k)}})});return out.slice(0,350)}
async function hydrateResources(text){
  const keys=resourceKeys(text);let cached=null;
  try{cached=Cache?await Cache.getBundle(keys):null}catch(_e){}
  if(cached){app.resourceBundle=cached;Core.setExternalResources(cached);renderResourceStatus();}
  if(!hasServer()){if(!cached){app.resourceBundle=null;Core.setExternalResources(null);renderResourceStatus();}return cached}
  try{const fresh=await gsCall('getHermeneiaResourceBundle',keys);app.resourceBundle=fresh;Core.setExternalResources(fresh);if(Cache)Cache.putBundle(fresh).catch(()=>{});renderResourceStatus();return fresh}catch(e){if(cached){app.resourceBundle=cached;Core.setExternalResources(cached);renderResourceStatus();return cached}Core.setExternalResources(null);app.resourceBundle=null;renderResourceStatus(e);return null}}
async function refreshResourceStatus(){if(!hasServer()){renderResourceStatus();return}try{app.resourceStatus=await gsCall('getStatus');renderResourceStatus();if(app.resourceStatus?.bible?.ready)loadBibleIndex()}catch(e){renderResourceStatus(e)}}
function renderResourceStatus(error=null){const box=$('#resourceStatusView');if(!box)return;if(error)return box.innerHTML=`<div class="alert danger">${esc(error.message||error)}</div>`;if(!hasServer())return box.innerHTML='<div class="alert info"><strong>Modo autônomo.</strong> O motor interno está ativo. Dicionário XML, ICF, Frame², valência, Bíblia e Drive entram quando este mesmo HTML é publicado pelo Apps Script.</div>';const st=app.resourceStatus;if(!st)return box.innerHTML='<div class="muted">Estado ainda não consultado.</div>';box.innerHTML=`<div class="resource-grid"><div><b>Dicionário</b><span>${st.lexicon?.ready?'pronto':'pendente'}</span></div><div><b>Recursos semânticos</b><span>${st.resources?.ready?'prontos':'pendentes'}</span></div><div><b>Bíblia</b><span>${st.bible?.ready?'pronta':'pendente'}</span></div><div><b>Consulta atual</b><span>${Object.keys(app.resourceBundle?.lexical||{}).length} verbetes</span></div></div>`}
async function loadBibleIndex(){try{app.bibleIndex=await gsCall('getBibleIndex');$('#bibleBook').innerHTML='<option value="">Selecione…</option>'+app.bibleIndex.map((b,i)=>`<option value="${i}">${esc(b.abbrev||String(i+1))}</option>`).join('')}catch(e){}}
async function insertBiblePassage(){if(!hasServer())return alert('A base bíblica requer Apps Script.');const b=Number($('#bibleBook').value);if(!Number.isFinite(b))return alert('Selecione o livro.');const c1=Math.max(1,+$('#bibleC1').value||1),v1=Math.max(1,+$('#bibleV1').value||1),c2=Math.max(c1,+$('#bibleC2').value||c1),v2=Math.max(1,+$('#bibleV2').value||v1);try{const r=await gsCall('getPassages',[{b,c1,v1,c2,v2}]),p=r?.[0];if(!p?.verses?.length)return alert('Passagem não encontrada.');const ab=app.bibleIndex?.[b]?.abbrev||`Livro ${b+1}`;const t=p.verses.map(x=>`${ab} ${x.c}.${x.v} ${x.t}`).join('\n');$('#sourceText').value=($('#sourceText').value.trim()?$('#sourceText').value.trim()+'\n':'')+t;if(!$('#title').value.trim())$('#title').value=`${ab} ${c1}.${v1}–${c2}.${v2}`}catch(e){alert(e.message||e)}}
async function prepareResources(){if(!hasServer())return alert('A preparação exige Apps Script.');if(!confirm('Preparar ou atualizar todos os recursos linguísticos?'))return;setStatus('Preparando recursos…','working');try{let plan=await gsCall('getPreparationPlan');if(!plan.bibleReady)await gsCall('prepareBible');for(const part of (plan.lexicon?.parts||[]).filter(x=>!(plan.lexicon?.done||[]).includes(x)))await gsCall('buildLexiconPart',part);await gsCall('finalizeLexicon');plan=await gsCall('getPreparationPlan');for(const r of plan.resources?.parts||[])if(!r.ready)await gsCall('buildResourcePart',r.id);await refreshResourceStatus();setStatus('Recursos prontos','good')}catch(e){setStatus('Erro nos recursos','bad');alert(e.message||e)}}

function addComment(){const text=$('#commentInput').value.trim();if(!app.selection?.quote)return alert('Selecione um trecho do texto.');if(!text)return alert('Escreva o comentário.');app.comments.push({role:$('#commentRole').value,text,quote:app.selection.quote,start:app.selection.start,end:app.selection.end,createdAt:new Date().toISOString()});$('#commentInput').value='';renderComments()}
function renderComments(){const box=$('#commentsList');if(!app.comments.length)return box.innerHTML='<div class="empty-state">Nenhum comentário humano registrado.</div>';box.innerHTML=app.comments.map((c,i)=>`<div class="comment-card ${c.role}"><div class="comment-head"><b>${c.role==='author'?'Autor':'Comentador'}</b><button type="button" class="icon-btn" data-rm-comment="${i}">×</button></div><div class="quote">“${esc(c.quote)}”</div><p>${esc(c.text)}</p></div>`).join('');$$('[data-rm-comment]').forEach(b=>b.onclick=()=>{app.comments.splice(+b.dataset.rmComment,1);renderComments()})}

async function analyze(){
  const text=$('#sourceText').value.trim();if(!text)return alert('Insira o texto.');
  const btn=$('#analyzeBtn');if(btn)btn.disabled=true;
  const stage=(label,p)=>setStatus(label+' · '+Math.round((p||0)*100)+'%','working');
  try{
    stage('Consultando recursos',.02);await hydrateResources(text);await new Promise(r=>setTimeout(r,0));
    app.analysis=await Core.analyzeAsync(text,options(),app.comments,(label,p)=>stage(label,.05+.55*p));
    await Deep.enrichAnalysis(app.analysis,(label,p)=>stage(label,.61+.16*p));
    stage('Calculando ambiguidade distribucional',.79);await new Promise(r=>setTimeout(r,0));
    app.analysis.ambiguity=Ambiguo.analyzeAnalysis(app.analysis,{maxTargets:14,minTargetFreq:2,minCollocates:4});
    stage('Construindo espaço hipotético',.86);await new Promise(r=>setTimeout(r,0));
    app.apotic=Hyp.generate(app.analysis,{localCap:50,beamWidth:50,finalCount:5,pinned:app.pinned});
    app.selectedFinals.clear();app.affirmed=null;app.researchQueries=[];app.researchResults=[];app.externalEvidence=[];
    stage('Renderizando relatórios',.96);await new Promise(r=>setTimeout(r,0));renderEverything();switchView('exegesis');setStatus('Análise concluída','good');
  }catch(e){console.error(e);setStatus('Falha','bad');window.HermeneiaUI?.showError(e,'análise');}
  finally{if(btn)btn.disabled=false}
}
function rerunHypotheses(){if(!app.analysis)return;app.apotic=Hyp.generate(app.analysis,{localCap:50,beamWidth:50,finalCount:5,pinned:app.pinned});app.selectedFinals.clear();renderApotic();renderHypothetical();setStatus('Hipóteses recalculadas','good')}

function renderEverything(){renderDashboard();renderExegesis();renderApotic();renderHypothetical();renderAffirmed();renderResearch();renderAudit()}
function renderDashboard(){const a=app.analysis,h=app.apotic;$('#analysisStats').innerHTML=`<div class="metric"><span>Unidades</span><b>${a.units.length}</b></div><div class="metric"><span>Blocos</span><b>${a.macro?.blocks?.length||0}</b></div><div class="metric"><span>Hipóteses locais</span><b>${h.stats.localTotal}</b></div><div class="metric"><span>Feixe global</span><b>${h.stats.beamWidth}</b></div><div class="metric accent"><span>Construções finais</span><b>${h.stats.finalCount}</b></div>`}

function defMapForUnit(a,id){const eq=(a.equideque||[]).find(e=>e.unit===id);const m=new Map();(eq?.literal||[]).forEach(x=>m.set(Core.norm(x.lemma),x));return m}
function featureText(t){if(t.pos==='punct')return'não se aplica';const lab={negation:'negação',modal:'modal',imperative:'imperativo',evaluation:'avaliação',cognition:'cognição',affect:'afeto','relative-free':'relativo livre/indefinido',singular:'singular',plural:'plural',masculine:'masculino',feminine:'feminino'};const xs=(t.features||[]).map(x=>lab[x]||x);if(t.number&&!['unknown','n/a'].includes(t.number)&&!xs.includes(lab[t.number]||t.number))xs.push(lab[t.number]||t.number);if(t.gender&&!['unknown','n/a'].includes(t.gender)&&!xs.includes(lab[t.gender]||t.gender))xs.push(lab[t.gender]||t.gender);return xs.filter(Boolean).join(', ')||'—'}
function shortDefinition(d){const defs=d?.definitions||[];if(!defs.length)return'—';const first=defs.slice(0,2).join('; ');const short=first.length>240?first.slice(0,237)+'…':first;if(defs.length<=2&&first.length<=240)return esc(short);return `<details class="lex-def"><summary>${esc(short)}</summary><div>${defs.map(x=>`<p>${esc(x)}</p>`).join('')}</div></details>`}
function renderMorphTable(a,u){const defs=defMapForUnit(a,u.id);return `<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Forma</th><th>Lema contextual</th><th>Classe contextual</th><th>Flexão / traços</th><th>Possibilidades da fonte lexical</th><th>Definição consultada</th></tr></thead><tbody>${(u.morph||[]).map((t,i)=>{const d=defs.get(Core.norm(t.lemma));return `<tr><td>${i+1}</td><td class="token-cell">${esc(t.surface)}</td><td>${esc(t.lemma)}</td><td>${esc(Hyp.POS_LABELS[t.pos]||t.pos)}</td><td>${esc(featureText(t))}</td><td>${esc((t.externalTags||[]).join(', ')||'—')}<small class="source-note">fonte; não decide a classe</small></td><td>${shortDefinition(d)}</td></tr>`}).join('')}</tbody></table></div>`}
function complementText(f){if(f.predicative)return `Predicativo: ${f.predicative.text}`;if(f.object)return f.object.text;return'—'}
function embeddedSyntax(f){if(!(f.embedded||[]).length)return'';return `<div class="embedded-syntax">${f.embedded.map(e=>`<div><b>${esc(e.label||e.type)}</b><span>Sujeito: ${esc(e.subject?.text||'—')}</span><span>Núcleo: ${esc(e.verb?.surface||e.verb?.lemma||'—')} → ${esc(e.verb?.lemma||'—')}</span><span>Complemento: ${esc(e.object?.text||'—')}</span><em>${pct(e.confidence||.7)}</em></div>`).join('')}</div>`}
function renderFrames(u){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Oração</th><th>Estrutura</th><th>Sujeito</th><th>Cópula / auxiliar(es)</th><th>Núcleo verbal</th><th>Complemento / predicativo</th><th>Negação</th><th>Modalidade</th><th>Frames / valência</th></tr></thead><tbody>${(u.frames||[]).map(f=>`<tr><td>${esc(f.text)}${embeddedSyntax(f)}</td><td>${esc(f.structure||'oração')}</td><td>${esc(f.subject?.text||'não expresso')}</td><td>${f.copular?`cópula: ${esc(f.verb?.surface||f.verb?.lemma||'—')}`:esc((f.auxiliaries||[]).map(x=>x.surface).join(' + ')||'—')}</td><td>${f.copular?'—':esc(f.verb?.lemma||'—')}</td><td>${esc(complementText(f))}</td><td>${f.negated?'sim':'não'}</td><td>${esc((f.modals||[]).join(', ')||u.modality||'—')}</td><td>${(f.semanticFrames||[]).length?(f.semanticFrames||[]).map(sf=>`<span class="evidence-chip">${esc(sf.frame)} ${pct(sf.support)}</span>`).join(' '):'—'}</td></tr>`).join('')}</tbody></table></div>`}

function renderDeepParse(u){const d=u.deepParse;if(!d||!d.nodes?.length)return '<div class="muted">Árvore de dependências indisponível.</div>';const node=i=>i===-1?{surface:'ROOT'}:d.nodeMap?.[i]||d.nodes.find(x=>x.index===i)||{surface:'?'};const edges=(d.edges||[]).filter(e=>e.label!=='root').sort((a,b)=>a.dependent-b.dependent);return `<div class="deep-note">A posição linear é tratada como evidência, não como função. Os arcos abaixo registram dependências propostas pelo parser Shift‑Reduce; arcos de baixa confiança permanecem classificatórios e não entram automaticamente na interpretação.</div><div class="dep-tree">${edges.map(e=>`<div class="dep-edge"><span>${esc(node(e.head).surface)}</span><span>→</span><span class="lab">${esc(window.HermeneiaDeepParser.depLabel(e.label))}</span><span>${esc(node(e.dependent).surface)}</span><span class="score">${pct(e.score)}</span></div>`).join('')}</div>`}
function renderHMM(u){const changed=(u.hmm||[]).filter(x=>x.changed);return changed.length?`<div class="deep-note"><b>HMM de fallback:</b> ${changed.map(x=>`${esc(x.surface)}: ${esc(x.original)} → ${esc(x.tag)} (${pct(x.confidence)})`).join('; ')}. Essas sugestões só servem quando a classificação lexical está fraca.</div>`:'<div class="muted">O HMM não precisou alterar candidatos morfológicos nesta unidade.</div>'}

function renderExegesis(){const a=app.analysis;if(!a)return;$('#exegesisHeader').innerHTML=`<div class="report-banner"><div><span class="eyebrow">RELATÓRIO 1 · EXEGESE</span><h2>${esc(a.title)}</h2><p>Relatório classificatório. Distingue forma, morfologia, encaixes sintáticos, predicação, regência e relações explicitamente observáveis. Etiquetas lexicais externas permanecem como possibilidades de consulta e não substituem a classificação contextual. Esta etapa não escolhe hipóteses interpretativas.</p></div><div class="report-seal">${esc(a.genre.genre)}<small>${pct(a.genre.confidence)}</small></div></div>`;
  $('#unitIndex').innerHTML=a.units.map(u=>`<button type="button" class="unit-index-btn" data-jump-unit="${u.id}"><b>${u.id}</b><span>${esc(u.text.slice(0,90))}${u.text.length>90?'…':''}</span></button>`).join('');
  $('#exegesisUnits').innerHTML=a.units.map(u=>`<section class="exe-unit" id="exe-${u.id}"><div class="exe-unit-head"><div><span class="unit-code">${u.id}</span><h3>${esc(u.text)}</h3></div><div class="unit-badges"><span>${esc(u.modality||'declarative')}</span><span>${u.clauses.length} oração(ões)</span></div></div><div class="exe-grid"><div class="analysis-panel full"><h4>Morfologia e léxico</h4>${renderMorphTable(a,u)}</div><div class="analysis-panel full"><h4>Sintaxe, predicação e valência</h4>${renderFrames(u)}</div><div class="analysis-panel full"><h4>Deep Parsing · árvore de dependências</h4>${renderDeepParse(u)}</div><div class="analysis-panel full"><h4>Fallback morfológico · HMM</h4>${renderHMM(u)}</div><div class="analysis-panel"><h4>Relações explicitamente detectadas</h4>${u.relations?.length?u.relations.map(r=>`<div class="fact-row"><b>${esc(r.type)}</b><span>marcador: ${esc(r.marker||'—')} · ${r.scope==='intraunit'?'relação interna à unidade':'candidata interunitária'}</span><em>${pct(r.confidence)}</em></div>`).join(''):'<div class="muted">Nenhuma relação explícita classificada nesta unidade.</div>'}</div><div class="analysis-panel"><h4>Estado epistêmico e temporal</h4>${[...(u.epistemic||[]).map(e=>`<div class="fact-row"><b>${esc(e.kind)}</b><span>epistêmico</span><em>${pct(e.confidence)}</em></div>`),...(u.temporal||[]).map(e=>`<div class="fact-row"><b>${esc(e.kind)}</b><span>temporal</span><em>${pct(e.confidence)}</em></div>`)].join('')||'<div class="muted">Sem marca especial.</div>'}</div></div></section>`).join('');
  const amb=a.ambiguity||{stats:{},targets:[]};$('#ambiguityView').innerHTML=`<div class="ambiguity-overview"><div class="ambiguity-metric"><span>Tokens do corpus</span><b>${amb.stats?.tokens||0}</b></div><div class="ambiguity-metric"><span>Alvos examinados</span><b>${amb.stats?.targetsExamined||0}</b></div><div class="ambiguity-metric"><span>Ambiguidades estatísticas</span><b>${amb.stats?.ambiguousTargets||0}</b></div></div>${(amb.targets||[]).map(t=>`<div class="ambiguity-item"><header><b>${esc(t.word)}</b><span>freq. ${t.frequency} · separação ${Number(t.separation||0).toFixed(3)}</span></header><div class="ambiguity-senses">${(t.senses||[]).map((s,i)=>`<span>S${i+1}: ${esc((s.label||[]).join(', '))}</span>`).join('')}</div></div>`).join('')||'<div class="muted">O texto não oferece corpus suficiente para separar sentidos por coocorrência com segurança. Isso não é falha: o módulo prefere não inventar grupos quando os dados são insuficientes.</div>'}`;
  const refs=[...(a.coreference||[]).map(x=>({kind:'pronome',expr:x.pronoun,target:x.entity,units:x.unit,conf:x.confidence})),...(a.discourseCoreference||[]).map(x=>({kind:'retomada discursiva',expr:x.expression,target:(x.terms||[]).join(', '),units:[...(x.antecedentUnits||[]),x.unit].join(' → '),conf:x.confidence})),...(a.deepCoreference||[]).map(x=>({kind:'correferência semântica · candidata',expr:x.pronoun,target:(x.candidates||[]).slice(0,3).map(c=>c.entity+' '+pct(c.score)).join(' / '),units:x.unit,conf:x.confidence}))];
  $('#referenceTable').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Tipo</th><th>Expressão</th><th>Referente / conjunto retomado</th><th>Unidades</th><th>Conf.</th></tr></thead><tbody>${refs.map(r=>`<tr><td>${esc(r.kind)}</td><td>${esc(r.expr)}</td><td>${esc(r.target)}</td><td>${esc(r.units)}</td><td>${pct(r.conf)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma correferência estabilizada.</td></tr>'}</tbody></table></div>`;
  $('#relationTable').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Origem</th><th>Destino</th><th>Relação</th><th>Base</th><th>Conf.</th></tr></thead><tbody>${[...(a.schLinks||[]).map(l=>({...l,_candidate:false})),...(a.rhetoricalHypotheses||[]).map(l=>({...l,_candidate:true}))].map(l=>`<tr><td>${esc(l.from)}</td><td>${esc(l.to)}</td><td>${esc(l.type)}${l._candidate?' · hipótese':''}</td><td>${esc(l.basis||'—')}</td><td>${pct(l.confidence)}</td></tr>`).join('')}</tbody></table></div>`;
  $$('[data-jump-unit]').forEach(b=>b.onclick=()=>document.querySelector(`#exe-${b.dataset.jumpUnit}`)?.scrollIntoView({behavior:'smooth',block:'start'}));
}

function renderApotic(){const a=app.analysis,h=app.apotic;if(!a||!h)return;$('#apoticPipeline').innerHTML=`<div class="pipeline"><div><span>1</span><b>Inteligência propõe</b><small>${h.stats.localTotal} hipóteses locais</small></div><i>→</i><div><span>2</span><b>Prorrelação compara</b><small>${h.stats.expansions.toLocaleString('pt-BR')} combinações avaliadas</small></div><i>→</i><div><span>3</span><b>Auteirética corta</b><small>${h.stats.pruned.toLocaleString('pt-BR')} caminhos podados</small></div><i>→</i><div><span>4</span><b>Retrointerpretação revisa</b><small>todo ↔ partes</small></div><i>→</i><div><span>5</span><b>Estado registra</b><small>${h.stats.beamWidth} sobreviventes</small></div></div>`;
  $('#apoticUnits').innerHTML=a.units.map(u=>{const hs=h.local[u.id]||[],pin=app.pinned[u.id];return `<details class="hyp-unit" ${u===a.units[0]?'open':''}><summary><div><b>${u.id}</b><span>${esc(u.text.slice(0,110))}${u.text.length>110?'…':''}</span></div><em>${hs.length} possibilidades${pin?' · 1 favorecida':''}</em></summary><div class="hyp-list">${hs.map(x=>`<article class="hyp-card ${pin===x.id?'pinned':''}"><div class="hyp-card-top"><div><span class="hyp-id">${x.id}</span><span class="lens ${x.lens}">${esc(x.family)}</span></div><strong>${pct(x.support)}</strong></div><p>${esc(x.statement)}</p><div class="evidence-line">${(x.evidence||[]).map(e=>`<span>${esc(e)}</span>`).join('')}</div>${x.assumptions?.length?`<div class="assumption">Dependência: ${esc(x.assumptions.join('; '))}</div>`:''}<div class="toolbar"><button type="button" class="mini-action" data-pin="${x.unitId}|${x.id}">${pin===x.id?'Remover preferência':'Favorecer nesta unidade'}</button><button type="button" class="mini-action ai" data-ai-explain="${x.unitId}|${x.id}">Explicar o que isso significa</button></div><div class="ai-explanation" data-ai-box="${x.unitId}|${x.id}" style="display:${app.aiHypothesisExplanations[x.unitId+'|'+x.id]?'block':'none'}">${app.aiHypothesisExplanations[x.unitId+'|'+x.id]?esc(app.aiHypothesisExplanations[x.unitId+'|'+x.id]):''}</div></article>`).join('')}</div></details>`}).join('');
  $$('[data-pin]').forEach(b=>b.onclick=()=>{const [u,id]=b.dataset.pin.split('|');if(app.pinned[u]===id)delete app.pinned[u];else app.pinned[u]=id;rerunHypotheses()});
  $$('[data-ai-explain]').forEach(b=>b.onclick=()=>{const [u,id]=b.dataset.aiExplain.split('|');const box=document.querySelector(`[data-ai-box="${CSS.escape(u+'|'+id)}"]`);if(box)box.style.display='block';explainHypothesisById(u,id)});
}

function renderHypothetical(){const h=app.apotic;if(!h)return;$('#beamStats').innerHTML=`<div class="beam-summary"><b>${h.stats.beamWidth}</b><span>interpretações globais sobreviventes</span><small>selecionadas depois de ${h.stats.expansions.toLocaleString('pt-BR')} comparações, com diversidade obrigatória entre caminhos</small></div>`;
  $('#finalConstructions').innerHTML=h.finals.map(f=>`<article class="construction ${app.selectedFinals.has(f.id)?'selected':''}"><header><div><span class="construction-rank">${f.rank}</span><span class="eyebrow">${esc(f.description)}</span><h3>${esc(f.title)}</h3></div><div class="score-ring"><b>${pct(f.score)}</b><small>coerência</small></div></header><p class="construction-summary">${esc(f.summary)}</p>${app.aiFinalExplanations[f.id]?`<div class="ai-explanation"><b>${esc(aiProviderLabel(app.aiFinalExplanations[f.id].provider))}${app.aiFinalExplanations[f.id].usesExternal?' · com apoio externo E':''}</b><div>${esc(app.aiFinalExplanations[f.id].text)}</div></div>`:''}<div class="construction-meta"><span>Cobertura macro: ${pct(f.coverage)}</span><span>Âncoras: ${esc(f.anchors.join(', ')||'—')}</span></div><details><summary>Evidências dominantes</summary>${f.supporting.map(c=>`<div class="evidence-item"><b>${esc(c.unitId)}</b><span>${esc(c.statement)}</span><em>${pct(c.support)}</em></div>`).join('')}</details><details><summary>Pontos frágeis / dependências</summary>${f.weakPoints.length?f.weakPoints.map(x=>`<div class="weak-item">${esc(x)}</div>`).join(''):'<div class="muted">Nenhum ponto abaixo do limiar de 62% entre as hipóteses escolhidas para este caminho.</div>'}</details><label class="select-construction"><input type="checkbox" data-final-select="${f.id}" ${app.selectedFinals.has(f.id)?'checked':''}> Usar esta construção na Derivação Afirmada</label></article>`).join('');
  $$('[data-final-select]').forEach(x=>x.onchange=()=>{if(x.checked)app.selectedFinals.add(x.dataset.finalSelect);else app.selectedFinals.delete(x.dataset.finalSelect);renderHypothetical();updateSelectionDock()});updateSelectionDock();
}
function updateSelectionDock(){const n=app.selectedFinals.size;$('#selectionCount').textContent=`${n} selecionada${n===1?'':'s'}`;$('#assumeBtn').disabled=!n}
function assumeSelection(){const finals=app.apotic.finals.filter(f=>app.selectedFinals.has(f.id));if(!finals.length)return;app.affirmed=Hyp.mergeFinals(finals,app.analysis);$('#readerThesis').value=app.affirmed.summary;renderAffirmed();switchView('affirmed');setStatus('Derivação selecionada pelo leitor','good')}
function macroLabel(x){return ({foundation:'fundamento/situação inicial',development:'desenvolvimento',problem:'problema',outcome:'resultado/avaliação',response:'resposta',closure:'fechamento',contrast:'contraste',explanation:'explicação',conclusion:'conclusão'}[x]||x||'bloco funcional')}
function relationHuman(x){return ({cause:'causa/explicação',consequence:'consequência',contrast:'contraste',concession:'concessão',condition:'condição',purpose:'finalidade',comparison:'comparação',reformulation:'reformulação',addition:'adição','referential-continuity':'continuidade referencial','frame-continuity':'continuidade semântica','anaphoric-resumption':'retomada anafórica','presence-absence-contrast':'contraste presença/ausência','polarity-contrast':'contraste de polaridade','structural-parallelism':'paralelismo estrutural','linear-progression':'progressão'}[x]||x||'progressão')}
async function realizeAffirmed(){
  if(!app.analysis||!app.affirmed)return alert('Selecione ao menos uma construção possível.');
  const thesis=$('#readerThesis').value.trim();if(!thesis)return alert('A Derivação Afirmada deve ser formulada ou aprovada pelo leitor.');
  const a=app.analysis,sel=app.affirmed,reg=$('#register').value,comp=sel.macroComposition||{},paras=[];
  setStatus('Compondo relatório final…','working');$('#affirmedReport').innerHTML='<div class="empty-state">Compondo e explicando a Derivação Afirmada…</div>';
  paras.push(`<section><h3>Leitura afirmada pelo leitor</h3><p>${esc(Realizer.fluencyPass(thesis,reg))}</p></section>`);
  const intro=`A passagem foi decomposta em ${a.units.length} unidades e reorganizada em ${a.macro?.blocks?.length||0} bloco${(a.macro?.blocks?.length||0)===1?'':'s'} funcionais. A formulação acima foi assumida pelo leitor depois da comparação entre ${app.apotic.stats.beamWidth} interpretações globais sobreviventes e das cinco construções apresentadas.`;
  paras.push(`<section><h3>Base metodológica</h3><p>${esc(Realizer.fluencyPass(intro,reg))}</p></section>`);
  const humanPlan=Redator.planFromAffirmedState(a,sel),humanText=Redator.write(humanPlan,{seed:a.sourceText+'|'+sel.id,mode:'reader'}).text;let developed=humanText||thesis;
  if($('#aiFinalPolish')?.checked){const internalData={origin:'T/L/U',sourceText:a.sourceText,readerThesis:thesis,macroComposition:comp,logicalText:humanText,relations:(comp.relations||[]),rule:'Use apenas T/L/U nesta seção; fontes E são proibidas aqui.'};const out=await HAI.run('final',internalData,{fallback:developed,maxNewTokens:700});developed=out.text;paras.push(`<section class="internal-ai"><h3>Explicação desenvolvida</h3><div class="muted">Realização: ${esc(aiProviderLabel(out.provider))} · conteúdo limitado ao Estado Semântico interno</div>${developed.split(/\n\n+/).map(p=>`<p>${esc(p)}</p>`).join('')}</section>`)}else if(developed)paras.push(`<section><h3>Explicação desenvolvida</h3>${developed.split(/\n\n+/).map(p=>`<p>${esc(p)}</p>`).join('')}</section>`);
  const blocks=(comp.blocks||[]).map(b=>`<div class="affirmed-block"><div class="affirmed-block-head"><b>${esc(b.id)}</b><span>${esc(macroLabel(b.role))}</span><em>${esc((b.unitIds||[]).join(' · '))}</em></div><p>${esc(Realizer.fluencyPass(b.text,reg))}</p><div class="muted">Âncoras: ${esc((b.anchors||[]).join(', ')||'—')} · suporte ${pct(b.support)}</div></div>`).join('');if(blocks)paras.push(`<section><h3>Composição macroargumentativa</h3><p>As hipóteses locais selecionadas foram comprimidas por bloco antes da redação. A leitura principal procura explicar a relação entre macroproposições, e não apenas repetir os rótulos das unidades.</p>${blocks}</section>`);
  const macroRels=(comp.relations||[]).map(r=>`<div class="evidence-item"><b>${esc(r.from)} → ${esc(r.to)}</b><span>${esc(relationHuman(r.type))}${r.basis?` · ${esc(r.basis)}`:''}</span><em>${pct(r.confidence||.64)}</em></div>`).join('');if(macroRels)paras.push(`<section><h3>Como as grandes partes se relacionam</h3>${macroRels}</section>`);
  const choiceByUnit=new Map();(sel.choices||[]).forEach(c=>{if(!choiceByUnit.has(c.unitId))choiceByUnit.set(c.unitId,[]);choiceByUnit.get(c.unitId).push(c)});let audit='';for(const u of a.units){const cs=(choiceByUnit.get(u.id)||[]).sort((x,y)=>y.support-x.support),unique=[];for(const c of cs){if(unique.length>=2)break;if(!unique.some(q=>q.family===c.family))unique.push(c)}if(!unique.length)continue;audit+=`<div class="affirmed-block"><div class="affirmed-block-head"><b>${esc(u.id)}</b><span>hipótese local</span><em>${esc(u.text.slice(0,70))}${u.text.length>70?'…':''}</em></div><p>${unique.map(c=>esc(c.statement)).join(' ')}</p></div>`}if(audit)paras.push(`<section><details><summary>Auditoria das hipóteses locais usadas na composição</summary><div class="field-spacer">${audit}</div></details></section>`);
  const ext=researchContext(10);if(ext.length&&$('#aiResearchEnrich')?.checked){const fallback='As fontes externas selecionadas oferecem material de comparação e contextualização, mas não alteram retroativamente a Exegese. A leitura dessas fontes deve permanecer distinguida daquilo que o próprio texto permitiu observar.';const out=await HAI.run('research',{origin:'E + comparação com U',readerThesis:thesis,internalSummary:sel.summary,external:ext},{fallback,maxNewTokens:620});paras.push(`<section class="external-ai"><h3>Aprofundamento externo</h3><div class="muted">Origem E · síntese por ${esc(aiProviderLabel(out.provider))}</div>${out.text.split(/\n\n+/).map(p=>`<p>${esc(p)}</p>`).join('')}<p class="muted">Esta seção não é evidência textual interna; ela registra apenas como fontes externas podem confirmar, qualificar, contradizer ou contextualizar a leitura escolhida.</p></section>`)}
  paras.push(`<section><h3>Limites</h3><p>A Exegese permanece separada desta derivação. Relações internas não são promovidas automaticamente a relações entre unidades; inferências estatísticas e relações assindéticas continuam hipóteses; fontes externas permanecem marcadas como E; e a interpretação global pertence ao leitor que a escolheu.</p></section>`);
  $('#affirmedReport').innerHTML=paras.join('');$('#affirmedMeta').textContent=`Construção(ões): ${sel.sourceFinals.join(', ')} · coerência média ${pct(sel.score)} · ${sel.anchors.length} âncoras · realizador ${aiProviderLabel(HAI.status().provider)}`;setStatus('Relatório final gerado','good');
}
function renderAffirmed(){if(!app.affirmed){$('#affirmedChoice').innerHTML='<div class="empty-state">Escolha uma ou mais das cinco construções no Relatório Hipotético. A Derivação Afirmada pertence ao leitor.</div>';$('#affirmedReport').innerHTML='';return}$('#affirmedChoice').innerHTML=`<div class="affirmed-choice"><span class="eyebrow">ESCOLHA DO LEITOR</span><h3>${esc(app.affirmed.title)}</h3><p>${esc(app.affirmed.summary)}</p><div class="evidence-line"><span>${app.affirmed.sourceFinals.join(' + ')}</span><span>${pct(app.affirmed.score)}</span></div></div>`}

function renderAudit(){const a=app.analysis,h=app.apotic;if(!a||!h)return;$('#auditFacts').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Tipo</th><th>Sujeito</th><th>Valor</th><th>Conf.</th><th>Âncoras</th></tr></thead><tbody>${a.state.list().map(f=>`<tr><td>${esc(f.type)}</td><td>${esc(f.subject)}</td><td class="mono">${esc(typeof f.value==='string'?f.value:JSON.stringify(f.value))}</td><td>${pct(f.confidence)}</td><td>${esc((f.anchors||[]).join(', '))}</td></tr>`).join('')}</tbody></table></div>`;$('#auditRejected').innerHTML=a.state.rejected.length?a.state.rejected.map(r=>`<div class="audit-reject"><b>${esc(r.type||'hipótese')}</b><span>${esc(r.reason||'rejeitada')}</span></div>`).join(''):'<div class="empty-state">Nenhuma rejeição canônica registrada pelo Engine.</div>';$('#auditBeam').innerHTML=`<div class="audit-cards"><div><span>Expansões</span><b>${h.stats.expansions.toLocaleString('pt-BR')}</b></div><div><span>Podas</span><b>${h.stats.pruned.toLocaleString('pt-BR')}</b></div><div><span>Feixe</span><b>${h.stats.beamWidth}</b></div><div><span>Robustez estrutural</span><b>${pct(a.robustness.score)}</b></div></div>`}


function researchStop(){return new Set('a o os as de do da dos das e ou em no na nos nas por para com sem um uma uns umas que se como mais menos não nao ao aos à às isto isso aquele aquela este esta ser estar ter haver texto passagem unidade análise analise interpretação interpretacao'.split(/\s+/))}
function textTokens(s){const stop=researchStop();return Core.words(Core.norm(s)).filter(w=>w.length>2&&!stop.has(w))}
function similarityText(a,b){const A=new Set(textTokens(a)),B=new Set(textTokens(b));if(!A.size||!B.size)return 0;let c=0;A.forEach(x=>{if(B.has(x))c++});return c/Math.sqrt(A.size*B.size)}
function analysisKeyTerms(){if(!app.analysis)return[];const macro=(app.analysis.macro?.blocks||[]).flatMap(b=>b.keyTerms||[]),concept=(app.analysis.concepts?.accepted||[]).flatMap(c=>c.hits||[]);return [...new Set([...macro,...concept].map(String).filter(Boolean))].slice(0,10)}
function detectReference(){const s=$('#title').value.trim()+' '+($('#sourceText').value.match(/^[^\n]{0,80}/)?.[0]||'');const m=s.match(/\b([1-3]?[A-Za-zÀ-ÿ]{2,18})\s+(\d{1,3})[\.:](\d{1,3})(?:\s*[–-]\s*(\d{1,3}))?/);return m?`${m[1]} ${m[2]}:${m[3]}${m[4]?'-'+m[4]:''}`:''}
function generateResearchQueries(){if(!app.analysis)return alert('Execute a análise primeiro.');const ref=detectReference(),title=$('#title').value.trim(),terms=analysisKeyTerms(),base=ref||title||terms.slice(0,3).join(' '),q=[];const add=(text,type)=>{text=String(text||'').replace(/\s+/g,' ').trim();if(text&&!q.some(x=>Core.norm(x.text)===Core.norm(text)))q.push({id:`Q${q.length+1}`,text,type})};add(`${base} ${terms.slice(0,3).join(' ')} análise sintática semântica`, 'linguística');if(terms[0])add(`${base} ${terms[0]} significado lexical campo semântico`, 'lexical');add(`${base} ${terms.slice(0,4).join(' ')} contexto histórico`, 'histórica');add(`${base} comentário exegético estudo acadêmico ${terms.slice(0,3).join(' ')}`, 'interpretativa');if(app.affirmed?.summary)add(`${base} ${terms.slice(0,3).join(' ')} ${app.affirmed.title}`, 'hipótese');app.researchQueries=q.slice(0,6);renderResearchQueries();setStatus('Consultas de aprofundamento geradas','good')}
function renderResearchQueries(){const box=$('#researchQueries');if(!box)return;box.innerHTML=app.researchQueries.length?app.researchQueries.map((q,i)=>`<div class="research-query"><input type="checkbox" data-rq-check="${i}" checked><input type="text" data-rq-text="${i}" value="${esc(q.text)}"><select data-rq-type="${i}"><option ${q.type==='linguística'?'selected':''}>linguística</option><option ${q.type==='lexical'?'selected':''}>lexical</option><option ${q.type==='histórica'?'selected':''}>histórica</option><option ${q.type==='interpretativa'?'selected':''}>interpretativa</option><option ${q.type==='hipótese'?'selected':''}>hipótese</option></select></div>`).join(''):'<div class="empty-state">Nenhuma consulta gerada.</div>'}
function researchDomains(){return $('#trustedDomains').value.split(/[\n,;]+/).map(x=>x.trim().replace(/^https?:\/\//,'').replace(/\/.*$/,'')).filter(Boolean)}
async function refreshWebSearchStatus(){if(!hasServer()){app.researchStatus={configured:false,reason:'Apps Script indisponível'};renderWebSearchStatus();return}try{app.researchStatus=await gsCall('getWebSearchStatus');renderWebSearchStatus()}catch(e){app.researchStatus={configured:false,error:e.message||String(e)};renderWebSearchStatus()}}
function renderWebSearchStatus(){const st=app.researchStatus||{},box=$('#webSearchStatus');if(!box)return;if(st.endpoint&&$('#searxEndpoint')&&!$('#searxEndpoint').value)$('#searxEndpoint').value=st.endpoint;box.innerHTML=st.configured?`<span class="source-meta"><span class="high">SearXNG configurado</span><span>${esc(st.endpoint||'')}</span></span>`:`<span class="source-meta"><span class="low">Informe uma instância SearXNG com JSON habilitado</span></span>${st.error?` · ${esc(st.error)}`:''}`}
async function saveSearchConfig(){if(!hasServer())return alert('A configuração da busca exige o Apps Script publicado.');const endpoint=$('#searxEndpoint').value.trim();if(!endpoint)return alert('Informe o endpoint da sua instância SearXNG.');try{app.researchStatus=await gsCall('saveWebSearchConfig',{provider:'searxng',endpoint});renderWebSearchStatus();setStatus('SearXNG salvo no backend','good')}catch(e){alert(e.message||e)}}
function selectedResearchQueries(){const out=[];$$('[data-rq-check]').forEach(ch=>{if(!ch.checked)return;const i=+ch.dataset.rqCheck,text=$(`[data-rq-text="${i}"]`).value.trim(),type=$(`[data-rq-type="${i}"]`).value;if(text)out.push({text,type})});return out}
function authorityClass(a){return a==='alta'?'high':a==='média'?'medium':'low'}
function renderResearchResults(){const box=$('#researchResults');if(!box)return;box.innerHTML=app.researchResults.length?app.researchResults.map((r,i)=>`<article class="source-card"><header><div><span class="external-origin">E · evidência externa</span><h4>${esc(r.title||r.url)}</h4><div class="source-meta"><span>${esc(r.sourceType||'web')}</span><span class="${authorityClass(r.authority)}">autoridade ${esc(r.authority||'não classificada')}</span><span>${esc(r.queryType||'consulta')}</span><span>${esc(r.domain||'')}</span></div></div><strong>${Math.round((r.searchScore||0)*100)}%</strong></header><p>${esc(r.description||'Sem resumo fornecido pelo mecanismo de busca.')}</p><div class="source-actions"><a href="${esc(r.url)}" target="_blank" rel="noopener">Abrir fonte</a><button type="button" data-read-source="${i}">Ler excerto</button><button type="button" data-attach-source="${i}">${app.externalEvidence.some(x=>x.url===r.url)?'Remover da evidência':'Anexar como evidência externa'}</button></div><div id="source-detail-${i}"></div></article>`).join(''):'<div class="empty-state">Nenhum resultado encontrado para os filtros atuais.</div>';$$('[data-attach-source]').forEach(b=>b.onclick=()=>toggleExternalEvidence(+b.dataset.attachSource));$$('[data-read-source]').forEach(b=>b.onclick=()=>readExternalSource(+b.dataset.readSource));$('#expandedReportBtn').disabled=!app.externalEvidence.length}
function toggleExternalEvidence(i){const r=app.researchResults[i];if(!r)return;const k=app.externalEvidence.findIndex(x=>x.url===r.url);if(k>=0)app.externalEvidence.splice(k,1);else app.externalEvidence.push({...r,origin:'E'});renderResearchResults();renderResearchComparison()}
function extractiveObservations(text,query){const terms=new Set([...textTokens(query),...analysisKeyTerms().slice(0,6).map(Core.norm)]),sent=String(text||'').split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(s=>s.length>40&&s.length<700);return sent.map(s=>{const t=textTokens(s);let hit=0;t.forEach(w=>{if(terms.has(w))hit++});return{s,score:hit/Math.sqrt(Math.max(1,t.length))}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.s.slice(0,320))}
async function readExternalSource(i){const r=app.researchResults[i];if(!r||!hasServer())return;const box=$(`#source-detail-${i}`);box.innerHTML='<div class="external-note">Consultando a página…</div>';try{const d=await gsCall('fetchWebSource',{url:r.url});const obs=extractiveObservations(d.text||'',r.query||'');box.innerHTML=`<div class="external-note"><b>Excerto analisado como E:</b>${obs.length?`<ul>${obs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:' não houve frases suficientemente relacionadas aos termos da análise.'}<small>Conteúdo externo não altera a Exegese.</small></div>`;r.extracted=obs}catch(e){box.innerHTML=`<div class="external-note">Não foi possível ler a fonte: ${esc(e.message||e)}</div>`}}
function compareExternalToFinals(){const finals=app.apotic?.finals||[],results=app.researchResults||[];return finals.map(f=>{const target=[f.summary,...(f.supporting||[]).map(x=>x.statement)].join(' '),scored=results.map(r=>({r,sim:similarityText(target,(r.title||'')+' '+(r.description||''))})).sort((a,b)=>b.sim-a.sim),top=scored.slice(0,3),weighted=top.length?top.reduce((s,x)=>s+x.sim*(x.r.authority==='alta'?1:x.r.authority==='média'?.8:.55),0)/top.length:0;return{final:f,score:Math.min(1,weighted*1.7),sources:top.filter(x=>x.sim>.05)}})}
function renderResearchComparison(){const box=$('#researchComparison');if(!box)return;const cmp=compareExternalToFinals();box.innerHTML=cmp.length?cmp.map(x=>`<div class="research-hyp"><div class="research-hyp-head"><b>${esc(x.final.id)} · ${esc(x.final.title)}</b><span>${pct(x.score)}</span></div><progress max="1" value="${x.score}"></progress><div class="muted">Correspondência documental potencial${x.sources.length?`: ${x.sources.map(s=>esc(s.r.domain)).join(', ')}`:' · sem correspondência suficiente'}.</div></div>`).join(''):'<div class="empty-state">As cinco construções aparecem depois da Apótica.</div>'}
async function runResearch(){if(!app.analysis)return alert('Execute a análise primeiro.');if(!hasServer())return alert('A pesquisa externa exige a versão publicada no Google Apps Script.');const queries=selectedResearchQueries();if(!queries.length)return alert('Selecione ao menos uma consulta.');setStatus('Pesquisando no SearXNG…','working');try{const data=await gsCall('searchWeb',{queries,mode:$('#researchMode').value,count:7,domains:researchDomains(),searchLang:'pt-BR'});app.researchResults=data.results||[];renderResearchResults();renderResearchComparison();setStatus(`${app.researchResults.length} resultados externos recuperados via SearXNG`,'good');if($('#aiResearchEnrich')?.checked&&app.apotic?.finals?.length)await enrichFinalsWithAI()}catch(e){setStatus('Falha na pesquisa externa','bad');alert(e.message||e)}}
async function generateExpandedResearchReport(){if(!app.externalEvidence.length)return;const thesis=$('#readerThesis').value.trim()||app.affirmed?.summary||'Nenhuma Derivação Afirmada foi registrada.';const items=app.externalEvidence.map(r=>`<div class="source-card"><span class="external-origin">E · ${esc(r.sourceType||'web')}</span><h4>${esc(r.title||r.url)}</h4><p>${esc(r.description||'')}</p>${r.extracted?.length?`<div class="external-note">${r.extracted.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<div class="muted">${esc(r.domain||'')} · autoridade ${esc(r.authority||'não classificada')} · <a href="${esc(r.url)}" target="_blank" rel="noopener">fonte</a></div></div>`).join('');let synthesis='';if($('#aiResearchEnrich')?.checked){setStatus('Comparando evidência externa com a leitura…','working');const out=await HAI.run('research',{origin:'E',readerThesis:thesis,external:researchContext(12),internal:{summary:app.affirmed?.summary||'',anchors:app.affirmed?.anchors||[]}},{fallback:'As fontes selecionadas servem como contexto e comparação externa. Elas não alteram automaticamente a leitura interna e precisam ser avaliadas quanto ao método, à proximidade com a questão e à autoridade.'});synthesis=`<div class="final-ai-box"><h4>Síntese comparativa</h4><div class="muted">${esc(aiProviderLabel(out.provider))}</div><p>${esc(out.text)}</p></div>`}$('#expandedResearchReport').innerHTML=`<div class="expanded-report"><h3>Leitura interna afirmada</h3><p>${esc(thesis)}</p><h3>Aprofundamento externo</h3><p>As fontes abaixo foram anexadas depois da interpretação interna. Elas permanecem marcadas como origem <b>E</b> e não alteram retroativamente os dados exegéticos.</p>${synthesis}${items}<h3>Limite metodológico</h3><p>Correspondência externa não equivale a confirmação automática. O leitor deve verificar método, contexto, autoria e qualidade de cada fonte antes de incorporá-la à própria formulação.</p></div>`;setStatus('Relatório externo ampliado gerado','good')}
function renderResearch(){renderResearchQueries();renderResearchResults();renderResearchComparison();renderWebSearchStatus()}

function serializeProject(){if(!app.analysis)return null;return {...Core.serialize(app.analysis),id:app.projectId||app.analysis.id||null,uiComments:app.comments,apotic:{stats:app.apotic?.stats,finals:app.apotic?.finals?.map(f=>({id:f.id,title:f.title,score:f.score,summary:f.summary,anchors:f.anchors}))},pinned:app.pinned,selectedFinals:[...app.selectedFinals],affirmed:app.affirmed,readerThesis:$('#readerThesis')?.value||'',externalEvidence:app.externalEvidence,researchQueries:app.researchQueries,aiHypothesisExplanations:app.aiHypothesisExplanations,aiFinalExplanations:app.aiFinalExplanations,ambiguity:app.analysis?.ambiguity||null,deepParser:app.analysis?.deepParser||null,deepCoreference:app.analysis?.deepCoreference||[],rhetoricalHypotheses:app.analysis?.rhetoricalHypotheses||[]}}
function exportJSON(){const d=serializeProject();if(!d)return;const b=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(d.title||'Hermeneia_4').replace(/[^\w-]+/g,'_')+'.json';a.click();URL.revokeObjectURL(a.href)}
async function saveProject(){const d=serializeProject();if(!d)return alert('Analise um texto primeiro.');if(!hasServer())return alert('Salvar no Drive requer Apps Script.');try{const r=await gsCall('saveProject',d);app.projectId=r.id||app.projectId;setStatus('Projeto salvo','good')}catch(e){alert(e.message||e)}}
async function refreshProjects(){const box=$('#projectsView');if(!hasServer())return box.innerHTML='<div class="alert info">A biblioteca do Drive aparece quando o HTML é publicado pelo Apps Script.</div>';box.innerHTML='<div class="empty-state">Carregando…</div>';try{const items=await gsCall('listProjects');box.innerHTML=(items||[]).map(p=>`<div class="project-row"><div><b>${esc(p.name)}</b><span>${new Date(p.updated).toLocaleString('pt-BR')}</span></div><button type="button" data-load-project="${esc(p.id)}">Abrir</button><button type="button" class="danger-text" data-del-project="${esc(p.id)}">Excluir</button></div>`).join('')||'<div class="empty-state">Nenhum projeto salvo.</div>';$$('[data-load-project]').forEach(b=>b.onclick=()=>loadProject(b.dataset.loadProject));$$('[data-del-project]').forEach(b=>b.onclick=()=>deleteProject(b.dataset.delProject))}catch(e){box.innerHTML=`<div class="alert danger">${esc(e.message||e)}</div>`}}
async function loadProject(id){try{const d=await gsCall('loadProject',id);$('#title').value=d.title||'';$('#sourceText').value=d.sourceText||'';$('#genre').value=d.options?.genre||'auto';$('#register').value=d.options?.register||'formal';$('#depth').value=d.options?.depth||'deep';app.comments=d.uiComments||[];app.pinned=d.pinned||{};app.projectId=d.id||id;renderComments();await analyze();app.externalEvidence=d.externalEvidence||[];app.researchQueries=d.researchQueries||[];renderResearch()}catch(e){alert(e.message||e)}}
async function deleteProject(id){if(!confirm('Excluir este projeto?'))return;try{await gsCall('deleteProject',id);refreshProjects()}catch(e){alert(e.message||e)}}

function printCurrent(){window.print()}

function bindClick(id,fn){if(!document.getElementById(id)){console.warn('Hermeneia: elemento ausente #'+id);return false;}return window.HermeneiaUI.register(id,fn)}
function bindEvents(){
  window.__HERMENEIA_NAV__=function(name){switchView(name);if(name==='library')refreshProjects();if(name==='research')refreshWebSearchStatus()};
  bindClick('analyzeBtn',analyze);
  bindClick('detectAIBtn',detectAI);bindClick('activateAIBtn',activateAI);
  bindClick('sampleBtn',()=>{$('#title').value='1Coríntios 1.10–17';$('#sourceText').value=SAMPLE;setStatus('Texto de teste carregado')});
  bindClick('clearBtn',()=>{$('#title').value='';$('#sourceText').value='';app.analysis=null;app.apotic=null;app.comments=[];app.pinned={};app.selectedFinals.clear();app.affirmed=null;app.researchQueries=[];app.researchResults=[];app.externalEvidence=[];renderComments();renderResearch();setStatus('Pronto')});
  const src=$('#sourceText');if(src)src.addEventListener('select',()=>{const q=src.value.slice(src.selectionStart,src.selectionEnd).trim();app.selection=q?{quote:q,start:src.selectionStart,end:src.selectionEnd}:null;$('#selectionPreview').textContent=q?`“${q.slice(0,240)}${q.length>240?'…':''}”`:'Nenhum trecho selecionado.'});
  bindClick('addCommentBtn',addComment);bindClick('assumeBtn',assumeSelection);bindClick('realizeBtn',realizeAffirmed);bindClick('exportBtn',exportJSON);bindClick('saveBtn',saveProject);bindClick('printBtn',printCurrent);bindClick('refreshResourcesBtn',refreshResourceStatus);bindClick('prepareResourcesBtn',prepareResources);bindClick('insertBibleBtn',insertBiblePassage);bindClick('refreshProjectsBtn',refreshProjects);bindClick('generateResearchQueriesBtn',generateResearchQueries);bindClick('runResearchBtn',runResearch);bindClick('enrichHypothesesBtn',enrichTopHypothesesWithAI);bindClick('saveSearchKeyBtn',saveSearchConfig);bindClick('expandedReportBtn',generateExpandedResearchReport);
}

bindEvents();
$('#title').value='1Coríntios 1.10–17';$('#sourceText').value=SAMPLE;try{const aip=localStorage.getItem('hermeneia.ai.pref'),aim=localStorage.getItem('hermeneia.ai.webgpuModel');if(aip&&$('#aiProviderPref'))$('#aiProviderPref').value=aip;if(aim&&$('#webgpuModel'))$('#webgpuModel').value=aim}catch(_e){}renderComments();renderResourceStatus();renderResearch();renderAIStatus(true).catch(()=>{});if(hasServer()){Promise.resolve().then(refreshResourceStatus).catch(console.error);Promise.resolve().then(refreshWebSearchStatus).catch(console.error);}
}

(function HermeneiaSafeStart(){
  function showRuntimeError(err, phase){
    try {
      var box=document.getElementById('runtimeError');
      if(box){
        var msg=(err&&err.message)?err.message:String(err||'Erro desconhecido');
        var stack=(err&&err.stack)?String(err.stack).split('\n').slice(0,4).join(' | '):'';
        box.classList.add('show');
        box.innerHTML='<b>Falha de inicialização do Hermeneia'+(phase?' · '+phase:'')+'</b><div>'+String(msg).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];})+'</div>'+(stack?'<code>'+String(stack).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];})+'</code>':'');
      }
    } catch(_) {}
  }
  function start(){
    if(window.__HERMENEIA_STARTED__) return;
    window.__HERMENEIA_STARTED__=true;
    try {
      if(!window.HermeneiaCore||!window.HermeneiaHypothesis||!window.HermeneiaRealizer||!window.HermeneiaDeepParser){throw new Error('Módulos essenciais não foram carregados no index.html.');}
      HermeneiaAppBootstrap();
      document.documentElement.setAttribute('data-hermeneia-ready','1');
    } catch(err){
      window.__HERMENEIA_STARTED__=false;
      console.error('Hermeneia bootstrap:',err);
      showRuntimeError(err,'bootstrap');
    }
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',start,{once:true});
  else setTimeout(start,0);
})();
